name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    PUBLIC_NODE_ENV: ${{ vars.PUBLIC_NODE_ENV }},
    PUBLIC_SAVED_CONFIG: ${{ vars.PUBLIC_SAVED_CONFIG }},
    PUBLIC_SAVED_CV_DETAILS: ${{ vars.PUBLIC_SAVED_CV_DETAILS }},
    PUBLIC_SAVED_JOBDESC: ${{ vars.PUBLIC_SAVED_JOBDESC }},
    PUBLIC_FILES_PATH: ${{ secrets.PUBLIC_FILES_PATH }}

jobs:
  test-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run Python tests
      run: |
        pytest backend/tests

  build-tauri:
    needs: [test-python]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: install Rust stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: install dependencies (ubuntu only)
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: install app dependencies and build it
      working-directory: ./desktop
      run: npm install && npm run tauri build
    - uses: tauri-apps/tauri-action@v0
